### ISSUE TITLE
dev正常，build报错

### ISSUE THREAD

**Issue by heibaimeng** [Bloss/vuepress-theme-yubisaki#1]
使用vuepress官方的目录结构；新版vuepress（0.8）中，dev正常，build报错：
getTitle为undefine
```
import { pathToComponentName, getTitle, getLang } from "@app/util";
```
具体报错信息如下：
```
$ npm run build

> vuepress@0.8.4 build C:\Users\Administrator\Desktop\vuepress
> node bin/vuepress build docs


Rendering static HTML...
Rendering page: /Error rendering /:
TypeError: undefined is not a function
    at VueComponent.created (node_modules/vuepress-theme-yubisaki/Layout.vue?31c1:127:0)
    at callHook (C:\Users\Administrator\Desktop\vuepress\node_modules\vue\dist\vue.runtime.common.js:2919:21)
    at VueComponent.Vue._init (C:\Users\Administrator\Desktop\vuepress\node_modules\vue\dist\vue.runtime.common.js:4628:5)
    at new VueComponent (C:\Users\Administrator\Desktop\vuepress\node_modules\vue\dist\vue.runtime.common.js:4796:12)
    at createComponentInstanceForVnode (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7342:10)
    at renderComponentInner (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7516:40)
    at renderComponent (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7491:5)
    at RenderContext.renderNode (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7407:5)
    at RenderContext.next (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:2428:14)
    at cachedWrite (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:2287:9)
    at renderElement (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7645:5)
    at renderNode (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7409:5)
    at render (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:7753:5)
    at Object.renderToString (C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:8232:9)
    at C:\Users\Administrator\Desktop\vuepress\node_modules\vue-server-renderer\build.js:8569:22
    at <anonymous>
```
使用0.7正常；

**Comment by Bloss** [comment]
add some script in the`package.json` at the root:
```
"scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
```
Then, `npm run docs:dev` or `npm run docs:build`
The script in the package.json will add `project/node_modules/.bin` to `PATH` variable, so we can find the path for vuepress theme

**Comment by Bloss** [comment]
fix in [84364](https://github.com/Bloss/vuepress-theme-yubisaki/commit/843646dfb54b7c5cc9fd7d85a569aec9f0139f52)
